version: "3.9"

services:
  examen-tercer-parcial:
    image: examen-tercer-parcial:1.0
    container_name: examen-tercer-parcial
    ports:
      - "8097:8097"
    environment:
      DB_URL: jdbc:mysql://host.docker.internal:3307/sisdb2025?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: abcd